version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: 'shouts.dev/laravel'
        container_name: shouts-laravel-app
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
        networks:
            - myNetwork
        depends_on:
            - db
    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
        - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: laravel
        volumes:
        - mysqldata:/var/lib/mysql/
        networks:
        - myNetwork
    # phpmyadmin
    phpmyadmin:
        image: 'phpmyadmin'
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PASSWORD: laravel
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8080:80
        networks:
            - myNetwork

networks:
    myNetwork:
        driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local